MAX_VARIABLES = 5
MIN_DERIVATIVE_ORDER = 1
MAX_DERIVATIVE_ORDER = 4

ALLOWED_VARIABLES = ("a", "b", "c", "d", "e")

SYMBOL_NOT = "!"
SYMBOL_AND = "&"
SYMBOL_OR = "|"
SYMBOL_IMPLIES = "->"
SYMBOL_EQUIVALENT = "~"
SYMBOL_OPEN_BRACKET = "("
SYMBOL_CLOSE_BRACKET = ")"

ZERO_TEXT = "0"
ONE_TEXT = "1"
EMPTY_TEXT = "ПУСТО"
